### ISSUE TITLE
Better handling of service location

### ISSUE THREAD

**Issue by rauanmayemir** [php-soap/encoding#26]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | no

#### Summary

Providers often put garbage addresses (like `http://localhost:8080/soap/service`) in their schemas and then direct consumers to override it with test/live endpoints in runtime.

For ext-soap, it was possible to use local wsdl files, but then set the endpoint location manually, thus overriding whatever there is in the wsdl file.

But with the new way of creating soap engine, there's currently no easy way to change the service location. It is taken strictly from the WSDL, so the only way currently is to add an http middleware.

**Comment by veewee** [comment]
Hello @rauanmayemir,

I don't think this library should care about that specifics: It uses a WSDL to encode / decode a SOAP payload given a WSDL schema.

In your case, the WSDL is not correct. There are some ways forward:

* Manipulate the address in the service port directly in the WSDL.
* Manipulate the address in the service port after reading the WSDL that is done in the `wsdl-reader` package. Currently there is no code for this from our side though.
* Provide a HTTP middleware that changes the base-url.

My personal preference here would be to overwrite it through the HTTP middleware. Since that location makes the most sense to me.

How would you see this?

**Comment by rauanmayemir** [comment]
Changing something directly in WSDL is not often possible, as I said, there are live and test endpoints which are set at runtime. I believe the second option is the best, i.e add an engine option that will propagate to manipulating the service port, but it's not very urgent.
I temporarily added a HTTP middleware that hijacks the PSR7 request and changes its uri.

> In your case, the WSDL is not correct. 

That being true, I've seen it to be the most ubiquitous approach. 🙈

**Comment by veewee** [comment]
@rauanmayemir 

Having it as an engine option is a bit hard, because you can use any transport. (not only psr-18)

You don't really need to write or maintain a custom middleware but use the default once provided by httplug:
https://docs.php-http.org/en/latest/plugins/request-uri-manipulations.html

```php
use Http\Discovery\HttpClientDiscovery;
use Http\Discovery\UriFactoryDiscovery;
use Http\Client\Common\PluginClient;
use Http\Client\Common\Plugin\BaseUriPlugin;


$plugin = new BaseUriPlugin(UriFactoryDiscovery::find()->createUri('https://domain.com:8000/api'), [
    // Always replace the host, even if this one is provided on the sent request. Available for AddHostPlugin.
    'replace' => true,
]));
```

That is at least what I am using in my implementation currently.

**Comment by rauanmayemir** [comment]
That looks good. (* deleting custom uri replacer middleware *)

**Comment by veewee** [comment]
Since it had been discussed: Closing this one for now
